package viduendpoint

import "webreaper/internal/domain/entity"

// defaultVoices Vidu 官方音色表（数据源：platform.vidu.cn 语音合成·音色列表，
// 共 302 条，按 voice_id 去重）。启动 seed 进 generation_voices 表，
// 客户端经 GET /api/v1/generation/voices 查询/筛选。
var defaultVoices = []entity.GenerationVoice{
	{VoiceID: "male-qn-qingse", Language: "中文 (普通话)", Name: "青涩青年音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-uLeoUwGWiQQZLiKH.mp3"},
	{VoiceID: "male-qn-jingying", Language: "中文 (普通话)", Name: "精英青年音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-7hgJgP689lvUsESC.mp3"},
	{VoiceID: "male-qn-badao", Language: "中文 (普通话)", Name: "霸道青年音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-ypZmFjxo84q476Ds.mp3"},
	{VoiceID: "male-qn-daxuesheng", Language: "中文 (普通话)", Name: "青年大学生音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-T4kIZ1khgduPiW2i.mp3"},
	{VoiceID: "female-shaonv", Language: "中文 (普通话)", Name: "少女音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-Zp3xnBAgMpkKN0fb.mp3"},
	{VoiceID: "female-yujie", Language: "中文 (普通话)", Name: "御姐音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-YiaFlpiWzo4Twkxb.mp3"},
	{VoiceID: "female-chengshu", Language: "中文 (普通话)", Name: "成熟女性音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-HCbEW2grkWSOVYXB.mp3"},
	{VoiceID: "female-tianmei", Language: "中文 (普通话)", Name: "甜美女性音色", SampleURL: "https://scene.vidu.zone/media-asset/072356-gc9rn0lig2Phdh1g.mp3"},
	{VoiceID: "male-qn-qingse-jingpin", Language: "中文 (普通话)", Name: "青涩青年音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072356-HnCFvXEmdYsw1aR3.mp3"},
	{VoiceID: "male-qn-jingying-jingpin", Language: "中文 (普通话)", Name: "精英青年音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-LE3qZSK6GAKVnYeW.mp3"},
	{VoiceID: "male-qn-badao-jingpin", Language: "中文 (普通话)", Name: "霸道青年音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-HYMATRMvsle2yt76.mp3"},
	{VoiceID: "male-qn-daxuesheng-jingpin", Language: "中文 (普通话)", Name: "青年大学生音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-5rEScknS588MBpFa.mp3"},
	{VoiceID: "female-shaonv-jingpin", Language: "中文 (普通话)", Name: "少女音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-76I89nNs8pI9KTnA.mp3"},
	{VoiceID: "female-yujie-jingpin", Language: "中文 (普通话)", Name: "御姐音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-cnSquEUZyUTm0EM3.mp3"},
	{VoiceID: "female-chengshu-jingpin", Language: "中文 (普通话)", Name: "成熟女性音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-BLBVdk5lacUOjTlv.mp3"},
	{VoiceID: "female-tianmei-jingpin", Language: "中文 (普通话)", Name: "甜美女性音色-beta", SampleURL: "https://scene.vidu.zone/media-asset/072357-aatAGT8Yrj5VlLhB.mp3"},
	{VoiceID: "clever_boy", Language: "中文 (普通话)", Name: "聪明男童", SampleURL: "https://scene.vidu.zone/media-asset/072357-iKVi4SXFzAD8hwr2.mp3"},
	{VoiceID: "cute_boy", Language: "中文 (普通话)", Name: "可爱男童", SampleURL: "https://scene.vidu.zone/media-asset/072358-74OupDa2hVtAiEC7.mp3"},
	{VoiceID: "lovely_girl", Language: "中文 (普通话)", Name: "萌萌女童", SampleURL: "https://scene.vidu.zone/media-asset/072358-lG8JoFnhYTMZF0u2.mp3"},
	{VoiceID: "cartoon_pig", Language: "中文 (普通话)", Name: "卡通猪小琪", SampleURL: "https://scene.vidu.zone/media-asset/072358-TEMSh2Ofg8Veq7tQ.mp3"},
	{VoiceID: "bingjiao_didi", Language: "中文 (普通话)", Name: "病娇弟弟", SampleURL: "https://scene.vidu.zone/media-asset/072358-Rv9wMGYjHki3XE0W.mp3"},
	{VoiceID: "junlang_nanyou", Language: "中文 (普通话)", Name: "俊朗男友", SampleURL: "https://scene.vidu.zone/media-asset/072358-apYWF4sTFAu4HT4n.mp3"},
	{VoiceID: "chunzhen_xuedi", Language: "中文 (普通话)", Name: "纯真学弟", SampleURL: "https://scene.vidu.zone/media-asset/072358-1mna0aj1O43QFJu4.mp3"},
	{VoiceID: "lengdan_xiongzhang", Language: "中文 (普通话)", Name: "冷淡学长", SampleURL: "https://scene.vidu.zone/media-asset/072358-YzI6fisVFXYBDZj8.mp3"},
	{VoiceID: "badao_shaoye", Language: "中文 (普通话)", Name: "霸道少爷", SampleURL: "https://scene.vidu.zone/media-asset/072359-IIt6p1U9NxkMp1Y6.mp3"},
	{VoiceID: "tianxin_xiaoling", Language: "中文 (普通话)", Name: "甜心小玲", SampleURL: "https://scene.vidu.zone/media-asset/072359-AqyIK6uEnVwlF6jh.mp3"},
	{VoiceID: "qiaopi_mengmei", Language: "中文 (普通话)", Name: "俏皮萌妹", SampleURL: "https://scene.vidu.zone/media-asset/072359-Oz5Tzdi3pbCJKq4T.mp3"},
	{VoiceID: "wumei_yujie", Language: "中文 (普通话)", Name: "妩媚御姐", SampleURL: "https://scene.vidu.zone/media-asset/072359-9eRzdU0O3KKxnSWR.mp3"},
	{VoiceID: "diadia_xuemei", Language: "中文 (普通话)", Name: "嗲嗲学妹", SampleURL: "https://scene.vidu.zone/media-asset/072359-QKczPrBYdkh7cYnk.mp3"},
	{VoiceID: "danya_xuejie", Language: "中文 (普通话)", Name: "淡雅学姐", SampleURL: "https://scene.vidu.zone/media-asset/072359-z9HkOg1rpDOTcEF6.mp3"},
	{VoiceID: "Chinese (Mandarin)_Reliable_Executive", Language: "中文 (普通话)", Name: "沉稳高管", SampleURL: "https://scene.vidu.zone/media-asset/072014-KyNan6ZbFWullcwA.mp3"},
	{VoiceID: "Chinese (Mandarin)_News_Anchor", Language: "中文 (普通话)", Name: "新闻女声", SampleURL: "https://scene.vidu.zone/media-asset/072014-HO8qN7HowLpDeSxk.mp3"},
	{VoiceID: "Chinese (Mandarin)_Mature_Woman", Language: "中文 (普通话)", Name: "傲娇御姐", SampleURL: "https://scene.vidu.zone/media-asset/072014-YRHkapPGWTi6AMpF.mp3"},
	{VoiceID: "Chinese (Mandarin)_Unrestrained_Young_Man", Language: "中文 (普通话)", Name: "不羁青年", SampleURL: "https://scene.vidu.zone/media-asset/072014-ErSH4gUWyXwoKm0N.mp3"},
	{VoiceID: "Arrogant_Miss", Language: "中文 (普通话)", Name: "嚣张小姐", SampleURL: "https://scene.vidu.zone/media-asset/072014-tN236iR4Y4UIYhtu.mp3"},
	{VoiceID: "Robot_Armor", Language: "中文 (普通话)", Name: "机械战甲", SampleURL: "https://scene.vidu.zone/media-asset/072014-QH6ZIG4sFWV5LG1n.mp3"},
	{VoiceID: "Chinese (Mandarin)_Kind-hearted_Antie", Language: "中文 (普通话)", Name: "热心大婶", SampleURL: "https://scene.vidu.zone/media-asset/072014-A1APFa473HjaBhVL.mp3"},
	{VoiceID: "Chinese (Mandarin)_HK_Flight_Attendant", Language: "中文 (普通话)", Name: "港普空姐", SampleURL: "https://scene.vidu.zone/media-asset/072014-krsfdA78yBt7Xo60.mp3"},
	{VoiceID: "Chinese (Mandarin)_Humorous_Elder", Language: "中文 (普通话)", Name: "搞笑大爷", SampleURL: "https://scene.vidu.zone/media-asset/072014-cE1nhz9ZGzIdBpzz.mp3"},
	{VoiceID: "Chinese (Mandarin)_Gentleman", Language: "中文 (普通话)", Name: "温润男声", SampleURL: "https://scene.vidu.zone/media-asset/072015-ireMGTMsZwkcvnpK.mp3"},
	{VoiceID: "Chinese (Mandarin)_Warm_Bestie", Language: "中文 (普通话)", Name: "温暖闺蜜", SampleURL: "https://scene.vidu.zone/media-asset/072015-gw8VczK4UgGq7PDT.mp3"},
	{VoiceID: "Chinese (Mandarin)_Male_Announcer", Language: "中文 (普通话)", Name: "播报男声", SampleURL: "https://scene.vidu.zone/media-asset/072015-7roXgurt9k7hKzFE.mp3"},
	{VoiceID: "Chinese (Mandarin)_Sweet_Lady", Language: "中文 (普通话)", Name: "甜美女声", SampleURL: "https://scene.vidu.zone/media-asset/072015-gPhnrlLLSAUkqlbb.mp3"},
	{VoiceID: "Chinese (Mandarin)_Southern_Young_Man", Language: "中文 (普通话)", Name: "南方小哥", SampleURL: "https://scene.vidu.zone/media-asset/072015-IBxrNvCcpPsftZPY.mp3"},
	{VoiceID: "Chinese (Mandarin)_Wise_Women", Language: "中文 (普通话)", Name: "阅历姐姐", SampleURL: "https://scene.vidu.zone/media-asset/072015-cAA4pkMzycpyJnS7.mp3"},
	{VoiceID: "Chinese (Mandarin)_Gentle_Youth", Language: "中文 (普通话)", Name: "温润青年", SampleURL: "https://scene.vidu.zone/media-asset/072016-SJM3A4MPLxkwTpPb.mp3"},
	{VoiceID: "Chinese (Mandarin)_Warm_Girl", Language: "中文 (普通话)", Name: "温暖少女", SampleURL: "https://scene.vidu.zone/media-asset/072016-YqsIYQx95ejnm60I.mp3"},
	{VoiceID: "Chinese (Mandarin)_Kind-hearted_Elder", Language: "中文 (普通话)", Name: "花甲奶奶", SampleURL: "https://scene.vidu.zone/media-asset/072016-thIywqHMOxldDrHy.mp3"},
	{VoiceID: "Chinese (Mandarin)_Cute_Spirit", Language: "中文 (普通话)", Name: "憨憨萌兽", SampleURL: "https://scene.vidu.zone/media-asset/072016-kETCNwyPyI1BCqbA.mp3"},
	{VoiceID: "Chinese (Mandarin)_Radio_Host", Language: "中文 (普通话)", Name: "电台男主播", SampleURL: "https://scene.vidu.zone/media-asset/072016-R9fYJ99T9l4aGNGS.mp3"},
	{VoiceID: "Chinese (Mandarin)_Lyrical_Voice", Language: "中文 (普通话)", Name: "抒情男声", SampleURL: "https://scene.vidu.zone/media-asset/072016-3ZBJxk5fdLq6RekB.mp3"},
	{VoiceID: "Chinese (Mandarin)_Straightforward_Boy", Language: "中文 (普通话)", Name: "率真弟弟", SampleURL: "https://scene.vidu.zone/media-asset/072016-qmBBLsW7U5IQd6LN.mp3"},
	{VoiceID: "Chinese (Mandarin)_Sincere_Adult", Language: "中文 (普通话)", Name: "真诚青年", SampleURL: "https://scene.vidu.zone/media-asset/072016-vzzOfzNfOWtNOyOM.mp3"},
	{VoiceID: "Chinese (Mandarin)_Gentle_Senior", Language: "中文 (普通话)", Name: "温柔学姐", SampleURL: "https://scene.vidu.zone/media-asset/072016-PaRQa8DijbAn6erR.mp3"},
	{VoiceID: "Chinese (Mandarin)_Stubborn_Friend", Language: "中文 (普通话)", Name: "嘴硬竹马", SampleURL: "https://scene.vidu.zone/media-asset/072017-x42a4pgimTBDxWpQ.mp3"},
	{VoiceID: "Chinese (Mandarin)_Crisp_Girl", Language: "中文 (普通话)", Name: "清脆少女", SampleURL: "https://scene.vidu.zone/media-asset/072017-Jj7rRcIUnwJMrD72.mp3"},
	{VoiceID: "Chinese (Mandarin)_Pure-hearted_Boy", Language: "中文 (普通话)", Name: "清澈邻家弟弟", SampleURL: "https://scene.vidu.zone/media-asset/072017-EA7Z2f1Ou5ZOfWNr.mp3"},
	{VoiceID: "Chinese (Mandarin)_Soft_Girl", Language: "中文 (普通话)", Name: "软软女孩", SampleURL: "https://scene.vidu.zone/media-asset/072017-zIeJmPyeMsvXTMPN.mp3"},
	{VoiceID: "Cantonese_ProfessionalHost（F)", Language: "中文 (粤语)", Name: "专业女主持", SampleURL: "https://scene.vidu.zone/media-asset/072017-ynsFX3cldjtl62xi.mp3"},
	{VoiceID: "Cantonese_GentleLady", Language: "中文 (粤语)", Name: "温柔女声", SampleURL: "https://scene.vidu.zone/media-asset/072017-IO6fp0FyZe6xaG49.mp3"},
	{VoiceID: "Cantonese_ProfessionalHost（M)", Language: "中文 (粤语)", Name: "专业男主持", SampleURL: "https://scene.vidu.zone/media-asset/072018-otv08JVnkSB0BLJz.mp3"},
	{VoiceID: "Cantonese_PlayfulMan", Language: "中文 (粤语)", Name: "活泼男声", SampleURL: "https://scene.vidu.zone/media-asset/072018-iaGnbP1ycuobRZ9C.mp3"},
	{VoiceID: "Cantonese_CuteGirl", Language: "中文 (粤语)", Name: "可爱女孩", SampleURL: "https://scene.vidu.zone/media-asset/072018-qVDF05yOHcXC2gdh.mp3"},
	{VoiceID: "Cantonese_KindWoman", Language: "中文 (粤语)", Name: "善良女声", SampleURL: "https://scene.vidu.zone/media-asset/072018-8NUCoRQQ6ABIPwJn.mp3"},
	{VoiceID: "Grinch", Language: "英文", Name: "Grinch", SampleURL: "https://scene.vidu.zone/media-asset/071752-jncRxGL1nuONbclk.mp3"},
	{VoiceID: "Rudolph", Language: "英文", Name: "Rudolph", SampleURL: "https://scene.vidu.zone/media-asset/071752-5FQ6r55BOWg4ZBPf.mp3"},
	{VoiceID: "Arnold", Language: "英文", Name: "Arnold", SampleURL: "https://scene.vidu.zone/media-asset/071753-AxmKuE7wxlY8zvNn.mp3"},
	{VoiceID: "Charming_Santa", Language: "英文", Name: "Charming Santa", SampleURL: "https://scene.vidu.zone/media-asset/071753-hxdVnrUyH9XaPFoU.mp3"},
	{VoiceID: "Charming_Lady", Language: "英文", Name: "Charming Lady", SampleURL: "https://scene.vidu.zone/media-asset/071753-8K2HCbrry1fMinoe.mp3"},
	{VoiceID: "Sweet_Girl", Language: "英文", Name: "Sweet Girl", SampleURL: "https://scene.vidu.zone/media-asset/071753-e9wzMCB7DmaEGuhu.mp3"},
	{VoiceID: "Cute_Elf", Language: "英文", Name: "Cute Elf", SampleURL: "https://scene.vidu.zone/media-asset/071753-DSs6yYFM7nhP3Y73.mp3"},
	{VoiceID: "Attractive_Girl", Language: "英文", Name: "Attractive Girl", SampleURL: "https://scene.vidu.zone/media-asset/071753-bYCPNmnU1xcDQPtr.mp3"},
	{VoiceID: "Serene_Woman", Language: "英文", Name: "Serene Woman", SampleURL: "https://scene.vidu.zone/media-asset/071753-yBDI9GT2weSnwxH0.mp3"},
	{VoiceID: "English_Trustworthy_Man", Language: "英文", Name: "Trustworthy Man", SampleURL: "https://scene.vidu.zone/media-asset/071753-4y46Ju6xokARFbnT.mp3"},
	{VoiceID: "English_Graceful_Lady", Language: "英文", Name: "Graceful Lady", SampleURL: "https://scene.vidu.zone/media-asset/071753-Y6s3YATSib937ns2.mp3"},
	{VoiceID: "English_Aussie_Bloke", Language: "英文", Name: "Aussie Bloke", SampleURL: "https://scene.vidu.zone/media-asset/071754-LZE06DgGPNkTRemt.mp3"},
	{VoiceID: "English_Whispering_girl", Language: "英文", Name: "Whispering girl", SampleURL: "https://scene.vidu.zone/media-asset/071754-x4OKV2I685LLHZlY.mp3"},
	{VoiceID: "English_Diligent_Man", Language: "英文", Name: "Diligent Man", SampleURL: "https://scene.vidu.zone/media-asset/071754-7VPK3SG8FT2Xuwl1.mp3"},
	{VoiceID: "English_Gentle-voiced_man", Language: "英文", Name: "Gentle-voiced man", SampleURL: "https://scene.vidu.zone/media-asset/071754-oWQQfWnzyzVKQRyq.mp3"},
	{VoiceID: "Japanese_IntellectualSenior", Language: "日文", Name: "Intellectual Senior", SampleURL: "https://scene.vidu.zone/media-asset/071603-QRh9iySZHS09EzZp.mp3"},
	{VoiceID: "Japanese_DecisivePrincess", Language: "日文", Name: "Decisive Princess", SampleURL: "https://scene.vidu.zone/media-asset/071603-2toFtXbWBYF4gMrJ.mp3"},
	{VoiceID: "Japanese_LoyalKnight", Language: "日文", Name: "Loyal Knight", SampleURL: "https://scene.vidu.zone/media-asset/071603-4AhKlHBRmVSqzIgT.mp3"},
	{VoiceID: "Japanese_DominantMan", Language: "日文", Name: "Dominant Man", SampleURL: "https://scene.vidu.zone/media-asset/071603-20uK33nB8EFTTBtl.mp3"},
	{VoiceID: "Japanese_SeriousCommander", Language: "日文", Name: "Serious Commander", SampleURL: "https://scene.vidu.zone/media-asset/071603-yqm2eRGX6YN86wSZ.mp3"},
	{VoiceID: "Japanese_ColdQueen", Language: "日文", Name: "Cold Queen", SampleURL: "https://scene.vidu.zone/media-asset/071603-J8Y40ENAYvWDSttc.mp3"},
	{VoiceID: "Japanese_DependableWoman", Language: "日文", Name: "Dependable Woman", SampleURL: "https://scene.vidu.zone/media-asset/071604-C9RsWj5tlZt36OWh.mp3"},
	{VoiceID: "Japanese_GentleButler", Language: "日文", Name: "Gentle Butler", SampleURL: "https://scene.vidu.zone/media-asset/071604-lWhG00rvnTuPPFSo.mp3"},
	{VoiceID: "Japanese_KindLady", Language: "日文", Name: "Kind Lady", SampleURL: "https://scene.vidu.zone/media-asset/071604-5jpras5x3poiOSGk.mp3"},
	{VoiceID: "Japanese_CalmLady", Language: "日文", Name: "Calm Lady", SampleURL: "https://scene.vidu.zone/media-asset/071604-wlDxbRTLNaIEbZ5M.mp3"},
	{VoiceID: "Japanese_OptimisticYouth", Language: "日文", Name: "Optimistic Youth", SampleURL: "https://scene.vidu.zone/media-asset/071604-vUsH8urJGa3tt7D8.mp3"},
	{VoiceID: "Japanese_GenerousIzakayaOwner", Language: "日文", Name: "Generous Izakaya Owner", SampleURL: "https://scene.vidu.zone/media-asset/071604-tPEQvxWFuQERuC6Q.mp3"},
	{VoiceID: "Japanese_SportyStudent", Language: "日文", Name: "Sporty Student", SampleURL: "https://scene.vidu.zone/media-asset/071605-IKwSl9VKF9rnf8S8.mp3"},
	{VoiceID: "Japanese_InnocentBoy", Language: "日文", Name: "Innocent Boy", SampleURL: "https://scene.vidu.zone/media-asset/071605-NVkeELYpcAOUr9wD.mp3"},
	{VoiceID: "Japanese_GracefulMaiden", Language: "日文", Name: "Graceful Maiden", SampleURL: "https://scene.vidu.zone/media-asset/071605-laBcWggCCv2p74YR.mp3"},
	{VoiceID: "Korean_SweetGirl", Language: "韩文", Name: "Sweet Girl", SampleURL: "https://scene.vidu.zone/media-asset/070800-9UMQFeOvRxi2QjeD.mp3"},
	{VoiceID: "Korean_CheerfulBoyfriend", Language: "韩文", Name: "Cheerful Boyfriend", SampleURL: "https://scene.vidu.zone/media-asset/070800-mjtmWUxmCKtJOLj5.mp3"},
	{VoiceID: "Korean_EnchantingSister", Language: "韩文", Name: "Enchanting Sister", SampleURL: "https://scene.vidu.zone/media-asset/070800-TuZar4xXGxG8BM7g.mp3"},
	{VoiceID: "Korean_ShyGirl", Language: "韩文", Name: "Shy Girl", SampleURL: "https://scene.vidu.zone/media-asset/070801-SSFgZHI4BKznJvWV.mp3"},
	{VoiceID: "Korean_ReliableSister", Language: "韩文", Name: "Reliable Sister", SampleURL: "https://scene.vidu.zone/media-asset/070801-DUF2wBkKhIJvuuU4.mp3"},
	{VoiceID: "Korean_StrictBoss", Language: "韩文", Name: "Strict Boss", SampleURL: "https://scene.vidu.zone/media-asset/070801-mGkkZFVCEfEQsOqM.mp3"},
	{VoiceID: "Korean_SassyGirl", Language: "韩文", Name: "Sassy Girl", SampleURL: "https://scene.vidu.zone/media-asset/070801-BoJIHHU2CKAlj2wB.mp3"},
	{VoiceID: "Korean_ChildhoodFriendGirl", Language: "韩文", Name: "Childhood Friend Girl", SampleURL: "https://scene.vidu.zone/media-asset/070801-eorNHI2o4GX93Fz1.mp3"},
	{VoiceID: "Korean_PlayboyCharmer", Language: "韩文", Name: "Playboy Charmer", SampleURL: "https://scene.vidu.zone/media-asset/070801-QzWsVtLtNttkosnn.mp3"},
	{VoiceID: "Korean_ElegantPrincess", Language: "韩文", Name: "Elegant Princess", SampleURL: "https://scene.vidu.zone/media-asset/070801-dCGGsWCXUTVj3ctt.mp3"},
	{VoiceID: "Korean_BraveFemaleWarrior", Language: "韩文", Name: "Brave Female Warrior", SampleURL: "https://scene.vidu.zone/media-asset/070802-ergTgls4uLTyLOCT.mp3"},
	{VoiceID: "Korean_BraveYouth", Language: "韩文", Name: "Brave Youth", SampleURL: "https://scene.vidu.zone/media-asset/070802-R5En7boVtcqlcJRi.mp3"},
	{VoiceID: "Korean_CalmLady", Language: "韩文", Name: "Calm Lady", SampleURL: "https://scene.vidu.zone/media-asset/070802-085EUwwXLvy9nhUa.mp3"},
	{VoiceID: "Korean_EnthusiasticTeen", Language: "韩文", Name: "Enthusiastic Teen", SampleURL: "https://scene.vidu.zone/media-asset/070802-VaqXim4fv6IoNk7C.mp3"},
	{VoiceID: "Korean_SoothingLady", Language: "韩文", Name: "Soothing Lady", SampleURL: "https://scene.vidu.zone/media-asset/070802-Os0s7Fxt6Rvm09So.mp3"},
	{VoiceID: "Korean_IntellectualSenior", Language: "韩文", Name: "Intellectual Senior", SampleURL: "https://scene.vidu.zone/media-asset/070802-njElfn743RgE2jvc.mp3"},
	{VoiceID: "Korean_LonelyWarrior", Language: "韩文", Name: "Lonely Warrior", SampleURL: "https://scene.vidu.zone/media-asset/070802-ov9mP4QiJIRENPLu.mp3"},
	{VoiceID: "Korean_MatureLady", Language: "韩文", Name: "Mature Lady", SampleURL: "https://scene.vidu.zone/media-asset/070802-yciPEHaaghSBWR7d.mp3"},
	{VoiceID: "Korean_InnocentBoy", Language: "韩文", Name: "Innocent Boy", SampleURL: "https://scene.vidu.zone/media-asset/070803-rAjCu3yh29pgal9V.mp3"},
	{VoiceID: "Korean_CharmingSister", Language: "韩文", Name: "Charming Sister", SampleURL: "https://scene.vidu.zone/media-asset/070803-LCF6CkbDlPSKVW14.mp3"},
	{VoiceID: "Korean_AthleticStudent", Language: "韩文", Name: "Athletic Student", SampleURL: "https://scene.vidu.zone/media-asset/070803-XWYLsx3kwiZ3b9sS.mp3"},
	{VoiceID: "Korean_BraveAdventurer", Language: "韩文", Name: "Brave Adventurer", SampleURL: "https://scene.vidu.zone/media-asset/070803-U1hIhDdUyQpqoZpr.mp3"},
	{VoiceID: "Korean_CalmGentleman", Language: "韩文", Name: "Calm Gentleman", SampleURL: "https://scene.vidu.zone/media-asset/070803-P5NbTLP8jrcp9LDN.mp3"},
	{VoiceID: "Korean_WiseElf", Language: "韩文", Name: "Wise Elf", SampleURL: "https://scene.vidu.zone/media-asset/070803-E9GisuGpHGPN2b6b.mp3"},
	{VoiceID: "Korean_CheerfulCoolJunior", Language: "韩文", Name: "Cheerful Cool Junior", SampleURL: "https://scene.vidu.zone/media-asset/070803-AdzPeNndz7mVhLhQ.mp3"},
	{VoiceID: "Korean_DecisiveQueen", Language: "韩文", Name: "Decisive Queen", SampleURL: "https://scene.vidu.zone/media-asset/070803-FVdlsrLJZEHtXZ17.mp3"},
	{VoiceID: "Korean_ColdYoungMan", Language: "韩文", Name: "Cold Young Man", SampleURL: "https://scene.vidu.zone/media-asset/070803-vocQv7J6ArLjp0TE.mp3"},
	{VoiceID: "Korean_MysteriousGirl", Language: "韩文", Name: "Mysterious Girl", SampleURL: "https://scene.vidu.zone/media-asset/070804-B8HBEX6r1e6e46kN.mp3"},
	{VoiceID: "Korean_QuirkyGirl", Language: "韩文", Name: "Quirky Girl", SampleURL: "https://scene.vidu.zone/media-asset/070804-54tAQsQkilJYlj5P.mp3"},
	{VoiceID: "Korean_ConsiderateSenior", Language: "韩文", Name: "Considerate Senior", SampleURL: "https://scene.vidu.zone/media-asset/070804-CDvdlovW4I47sCOL.mp3"},
	{VoiceID: "Korean_CheerfulLittleSister", Language: "韩文", Name: "Cheerful Little Sister", SampleURL: "https://scene.vidu.zone/media-asset/070804-hghwpVvHn2vYHNWO.mp3"},
	{VoiceID: "Korean_DominantMan", Language: "韩文", Name: "Dominant Man", SampleURL: "https://scene.vidu.zone/media-asset/070804-yguQNBsKsSBMPam6.mp3"},
	{VoiceID: "Korean_AirheadedGirl", Language: "韩文", Name: "Airheaded Girl", SampleURL: "https://scene.vidu.zone/media-asset/070804-ELTyvSCKZEjYl3s0.mp3"},
	{VoiceID: "Korean_ReliableYouth", Language: "韩文", Name: "Reliable Youth", SampleURL: "https://scene.vidu.zone/media-asset/070805-FiWsHtV4TP7dzuvz.mp3"},
	{VoiceID: "Korean_FriendlyBigSister", Language: "韩文", Name: "Friendly Big Sister", SampleURL: "https://scene.vidu.zone/media-asset/070805-V5evipalTiDD9nvH.mp3"},
	{VoiceID: "Korean_GentleBoss", Language: "韩文", Name: "Gentle Boss", SampleURL: "https://scene.vidu.zone/media-asset/070805-kGckiiwRRzgO3RVA.mp3"},
	{VoiceID: "Korean_ColdGirl", Language: "韩文", Name: "Cold Girl", SampleURL: "https://scene.vidu.zone/media-asset/070805-9ZjegsY9vM93LevN.mp3"},
	{VoiceID: "Korean_HaughtyLady", Language: "韩文", Name: "Haughty Lady", SampleURL: "https://scene.vidu.zone/media-asset/070805-NwKD9mhTxLaLx5D9.mp3"},
	{VoiceID: "Korean_CharmingElderSister", Language: "韩文", Name: "Charming Elder Sister", SampleURL: "https://scene.vidu.zone/media-asset/070805-sj7vyOyPyVWBGwbU.mp3"},
	{VoiceID: "Korean_IntellectualMan", Language: "韩文", Name: "Intellectual Man", SampleURL: "https://scene.vidu.zone/media-asset/070805-HrwswOtNNHbf1WSL.mp3"},
	{VoiceID: "Korean_CaringWoman", Language: "韩文", Name: "Caring Woman", SampleURL: "https://scene.vidu.zone/media-asset/070805-9feq1GPW2I8TDjvf.mp3"},
	{VoiceID: "Korean_WiseTeacher", Language: "韩文", Name: "Wise Teacher", SampleURL: "https://scene.vidu.zone/media-asset/070805-V18z7I9BacTBWmdr.mp3"},
	{VoiceID: "Korean_ConfidentBoss", Language: "韩文", Name: "Confident Boss", SampleURL: "https://scene.vidu.zone/media-asset/070806-QdCZt0Y6POMi00De.mp3"},
	{VoiceID: "Korean_AthleticGirl", Language: "韩文", Name: "Athletic Girl", SampleURL: "https://scene.vidu.zone/media-asset/070806-eH1gvEUmehqm6KAd.mp3"},
	{VoiceID: "Korean_PossessiveMan", Language: "韩文", Name: "Possessive Man", SampleURL: "https://scene.vidu.zone/media-asset/070806-F8xofvm8HZfePrc4.mp3"},
	{VoiceID: "Korean_GentleWoman", Language: "韩文", Name: "Gentle Woman", SampleURL: "https://scene.vidu.zone/media-asset/070806-0PwqHf6TTcXHpgTk.mp3"},
	{VoiceID: "Korean_CockyGuy", Language: "韩文", Name: "Cocky Guy", SampleURL: "https://scene.vidu.zone/media-asset/070806-MA182ManXRurk827.mp3"},
	{VoiceID: "Korean_ThoughtfulWoman", Language: "韩文", Name: "Thoughtful Woman", SampleURL: "https://scene.vidu.zone/media-asset/070806-ln9rt4eTeJtp8zUc.mp3"},
	{VoiceID: "Korean_OptimisticYouth", Language: "韩文", Name: "Optimistic Youth", SampleURL: "https://scene.vidu.zone/media-asset/070806-4tX7Kfu8PnSWJAzM.mp3"},
	{VoiceID: "Spanish_SereneWoman", Language: "西班牙文", Name: "Serene Woman", SampleURL: "https://scene.vidu.zone/media-asset/070348-UoReuAOn6CTUdFKy.mp3"},
	{VoiceID: "Spanish_MaturePartner", Language: "西班牙文", Name: "Mature Partner", SampleURL: "https://scene.vidu.zone/media-asset/070348-7WnSyhf1GhpCsoMw.mp3"},
	{VoiceID: "Spanish_CaptivatingStoryteller", Language: "西班牙文", Name: "Captivating Storyteller", SampleURL: "https://scene.vidu.zone/media-asset/070348-PGyDV29JR9dJ2VgT.mp3"},
	{VoiceID: "Spanish_Narrator", Language: "西班牙文", Name: "Narrator", SampleURL: "https://scene.vidu.zone/media-asset/070349-PRZutZ6UeOPHCSYG.mp3"},
	{VoiceID: "Spanish_WiseScholar", Language: "西班牙文", Name: "Wise Scholar", SampleURL: "https://scene.vidu.zone/media-asset/070349-gybZkG82B0KOjBsI.mp3"},
	{VoiceID: "Spanish_Kind-heartedGirl", Language: "西班牙文", Name: "Kind-hearted Girl", SampleURL: "https://scene.vidu.zone/media-asset/070349-bYiRLGRYXNE1rk6W.mp3"},
	{VoiceID: "Spanish_DeterminedManager", Language: "西班牙文", Name: "Determined Manager", SampleURL: "https://scene.vidu.zone/media-asset/070349-7gi92LMSHEzsX9Kj.mp3"},
	{VoiceID: "Spanish_BossyLeader", Language: "西班牙文", Name: "Bossy Leader", SampleURL: "https://scene.vidu.zone/media-asset/070349-4NnLw9Fb47nBWTHl.mp3"},
	{VoiceID: "Spanish_ReservedYoungMan", Language: "西班牙文", Name: "Reserved Young Man", SampleURL: "https://scene.vidu.zone/media-asset/070349-YKV7CZOpLJ9k6SLc.mp3"},
	{VoiceID: "Spanish_ConfidentWoman", Language: "西班牙文", Name: "Confident Woman", SampleURL: "https://scene.vidu.zone/media-asset/070349-Sc11mXoLeuzpZclC.mp3"},
	{VoiceID: "Spanish_ThoughtfulMan", Language: "西班牙文", Name: "Thoughtful Man", SampleURL: "https://scene.vidu.zone/media-asset/070349-fVT2wAMyiFAAb6y6.mp3"},
	{VoiceID: "Spanish_Strong-WilledBoy", Language: "西班牙文", Name: "Strong-willed Boy", SampleURL: "https://scene.vidu.zone/media-asset/070350-A7rCZfmbP6pdrDnR.mp3"},
	{VoiceID: "Spanish_SophisticatedLady", Language: "西班牙文", Name: "Sophisticated Lady", SampleURL: "https://scene.vidu.zone/media-asset/070350-a2rPvecdnw2Iw60m.mp3"},
	{VoiceID: "Spanish_RationalMan", Language: "西班牙文", Name: "Rational Man", SampleURL: "https://scene.vidu.zone/media-asset/070350-SqRmKH5xSvmRiFnu.mp3"},
	{VoiceID: "Spanish_AnimeCharacter", Language: "西班牙文", Name: "Anime Character", SampleURL: "https://scene.vidu.zone/media-asset/070350-I7IpRZADL89QmNr4.mp3"},
	{VoiceID: "Spanish_Deep-tonedMan", Language: "西班牙文", Name: "Deep-toned Man", SampleURL: "https://scene.vidu.zone/media-asset/070350-JwMDuPnqCNNW5IBh.mp3"},
	{VoiceID: "Spanish_Fussyhostess", Language: "西班牙文", Name: "Fussy hostess", SampleURL: "https://scene.vidu.zone/media-asset/070350-IGuZpp48aM8yY2Q1.mp3"},
	{VoiceID: "Spanish_SincereTeen", Language: "西班牙文", Name: "Sincere Teen", SampleURL: "https://scene.vidu.zone/media-asset/070350-Zx4RHy7L8MXfeaO3.mp3"},
	{VoiceID: "Spanish_FrankLady", Language: "西班牙文", Name: "Frank Lady", SampleURL: "https://scene.vidu.zone/media-asset/070351-a8bCoh4IPbRuCM5t.mp3"},
	{VoiceID: "Spanish_Comedian", Language: "西班牙文", Name: "Comedian", SampleURL: "https://scene.vidu.zone/media-asset/070351-kGXsC7vw2Adroyb0.mp3"},
	{VoiceID: "Spanish_Debator", Language: "西班牙文", Name: "Debator", SampleURL: "https://scene.vidu.zone/media-asset/070351-PS3VY7ripY9uOCZS.mp3"},
	{VoiceID: "Spanish_ToughBoss", Language: "西班牙文", Name: "Tough Boss", SampleURL: "https://scene.vidu.zone/media-asset/070351-oFFfNws2IzDsB3mN.mp3"},
	{VoiceID: "Spanish_Wiselady", Language: "西班牙文", Name: "Wise Lady", SampleURL: "https://scene.vidu.zone/media-asset/070351-rsBnYfrjJEdtwIO0.mp3"},
	{VoiceID: "Spanish_Steadymentor", Language: "西班牙文", Name: "Steady Mentor", SampleURL: "https://scene.vidu.zone/media-asset/070351-E07E5IJbNT2BpU7i.mp3"},
	{VoiceID: "Spanish_Jovialman", Language: "西班牙文", Name: "Jovial Man", SampleURL: "https://scene.vidu.zone/media-asset/070351-agsQVyTWeHc8sg2m.mp3"},
	{VoiceID: "Spanish_SantaClaus", Language: "西班牙文", Name: "Santa Claus", SampleURL: "https://scene.vidu.zone/media-asset/070351-q2Aip3axlveDRoT6.mp3"},
	{VoiceID: "Spanish_Rudolph", Language: "西班牙文", Name: "Rudolph", SampleURL: "https://scene.vidu.zone/media-asset/070351-3sar9F7Mzmb9HxsB.mp3"},
	{VoiceID: "Spanish_Intonategirl", Language: "西班牙文", Name: "Intonate Girl", SampleURL: "https://scene.vidu.zone/media-asset/070352-T7spxLWURyEpAXBU.mp3"},
	{VoiceID: "Spanish_Arnold", Language: "西班牙文", Name: "Arnold", SampleURL: "https://scene.vidu.zone/media-asset/070352-s0BE4PMDHdgFM6B7.mp3"},
	{VoiceID: "Spanish_Ghost", Language: "西班牙文", Name: "Ghost", SampleURL: "https://scene.vidu.zone/media-asset/070352-EFd8ZbN5bkFQLFZD.mp3"},
	{VoiceID: "Spanish_HumorousElder", Language: "西班牙文", Name: "Humorous Elder", SampleURL: "https://scene.vidu.zone/media-asset/070352-doZ3HajXy0fVStme.mp3"},
	{VoiceID: "Spanish_EnergeticBoy", Language: "西班牙文", Name: "Energetic Boy", SampleURL: "https://scene.vidu.zone/media-asset/070352-dXiikyTM3I1PETQJ.mp3"},
	{VoiceID: "Spanish_WhimsicalGirl", Language: "西班牙文", Name: "Whimsical Girl", SampleURL: "https://scene.vidu.zone/media-asset/070352-DlLwt9TbRy8FyJmt.mp3"},
	{VoiceID: "Spanish_StrictBoss", Language: "西班牙文", Name: "Strict Boss", SampleURL: "https://scene.vidu.zone/media-asset/070352-YGHLV8bEitcCbrVs.mp3"},
	{VoiceID: "Spanish_ReliableMan", Language: "西班牙文", Name: "Reliable Man", SampleURL: "https://scene.vidu.zone/media-asset/070352-2qTxwDoZM5Lfgl8q.mp3"},
	{VoiceID: "Spanish_SereneElder", Language: "西班牙文", Name: "Serene Elder", SampleURL: "https://scene.vidu.zone/media-asset/070352-sPdXlPqdTJ0vbUgl.mp3"},
	{VoiceID: "Spanish_AngryMan", Language: "西班牙文", Name: "Angry Man", SampleURL: "https://scene.vidu.zone/media-asset/070353-wMFRpWf3HJtM1UFj.mp3"},
	{VoiceID: "Spanish_AssertiveQueen", Language: "西班牙文", Name: "Assertive Queen", SampleURL: "https://scene.vidu.zone/media-asset/070353-SOB6ejA1vbx9Ew2p.mp3"},
	{VoiceID: "Spanish_CaringGirlfriend", Language: "西班牙文", Name: "Caring Girlfriend", SampleURL: "https://scene.vidu.zone/media-asset/070353-z24jAExWjbtgZLeB.mp3"},
	{VoiceID: "Spanish_PowerfulSoldier", Language: "西班牙文", Name: "Powerful Soldier", SampleURL: "https://scene.vidu.zone/media-asset/070353-l6f5Aclawcu2Rc2f.mp3"},
	{VoiceID: "Spanish_PassionateWarrior", Language: "西班牙文", Name: "Passionate Warrior", SampleURL: "https://scene.vidu.zone/media-asset/070353-9tKsw355jAMoch00.mp3"},
	{VoiceID: "Spanish_ChattyGirl", Language: "西班牙文", Name: "Chatty Girl", SampleURL: "https://scene.vidu.zone/media-asset/070353-8s7xO5eZuODxqnVp.mp3"},
	{VoiceID: "Spanish_RomanticHusband", Language: "西班牙文", Name: "Romantic Husband", SampleURL: "https://scene.vidu.zone/media-asset/070353-97u2UFJuOzP9KuZ5.mp3"},
	{VoiceID: "Spanish_CompellingGirl", Language: "西班牙文", Name: "Compelling Girl", SampleURL: "https://scene.vidu.zone/media-asset/070353-jFRPs3IACR6s98FO.mp3"},
	{VoiceID: "Spanish_PowerfulVeteran", Language: "西班牙文", Name: "Powerful Veteran", SampleURL: "https://scene.vidu.zone/media-asset/070353-qTcs6fwjkUCkWoeg.mp3"},
	{VoiceID: "Spanish_SensibleManager", Language: "西班牙文", Name: "Sensible Manager", SampleURL: "https://scene.vidu.zone/media-asset/070354-gnAWCgi02ly0jK1a.mp3"},
	{VoiceID: "Spanish_ThoughtfulLady", Language: "西班牙文", Name: "Thoughtful Lady", SampleURL: "https://scene.vidu.zone/media-asset/070354-Cog8TJzC2MmtLFub.mp3"},
	{VoiceID: "Portuguese_SentimentalLady", Language: "葡萄牙文", Name: "Sentimental Lady", SampleURL: "https://scene.vidu.zone/media-asset/035852-YlDdiriZ28E7YPD3.mp3"},
	{VoiceID: "Portuguese_BossyLeader", Language: "葡萄牙文", Name: "Bossy Leader", SampleURL: "https://scene.vidu.zone/media-asset/035852-HoggtsELGRNc3GE8.mp3"},
	{VoiceID: "Portuguese_Wiselady", Language: "葡萄牙文", Name: "Wise lady", SampleURL: "https://scene.vidu.zone/media-asset/035852-kFdHiHIUzA4DqmkY.mp3"},
	{VoiceID: "Portuguese_Strong-WilledBoy", Language: "葡萄牙文", Name: "Strong-willed Boy", SampleURL: "https://scene.vidu.zone/media-asset/035854-FQnA7navsy0NEpPH.mp3"},
	{VoiceID: "Portuguese_Deep-VoicedGentleman", Language: "葡萄牙文", Name: "Deep-voiced Gentleman", SampleURL: "https://scene.vidu.zone/media-asset/035853-wJtnnAnKT6HUGhDq.mp3"},
	{VoiceID: "Portuguese_UpsetGirl", Language: "葡萄牙文", Name: "Upset Girl", SampleURL: "https://scene.vidu.zone/media-asset/035853-jBFprcgHgXk3KHJ0.mp3"},
	{VoiceID: "Portuguese_PassionateWarrior", Language: "葡萄牙文", Name: "Passionate Warrior", SampleURL: "https://scene.vidu.zone/media-asset/035854-rMppnUCpkVnOLyS7.mp3"},
	{VoiceID: "Portuguese_AnimeCharacter", Language: "葡萄牙文", Name: "Anime Character", SampleURL: "https://scene.vidu.zone/media-asset/035854-n3daCwqnRBEvicdE.mp3"},
	{VoiceID: "Portuguese_ConfidentWoman", Language: "葡萄牙文", Name: "Confident Woman", SampleURL: "https://scene.vidu.zone/media-asset/035854-tfBs4WaHLxMrxpgY.mp3"},
	{VoiceID: "Portuguese_AngryMan", Language: "葡萄牙文", Name: "Angry Man", SampleURL: "https://scene.vidu.zone/media-asset/035855-awE9rIRE6CCX7cr3.mp3"},
	{VoiceID: "Portuguese_CaptivatingStoryteller", Language: "葡萄牙文", Name: "Captivating Storyteller", SampleURL: "https://scene.vidu.zone/media-asset/035855-veYMckFU2ePNhhed.mp3"},
	{VoiceID: "Portuguese_Godfather", Language: "葡萄牙文", Name: "Godfather", SampleURL: "https://scene.vidu.zone/media-asset/035855-FMP1Um96WiGR5XPi.mp3"},
	{VoiceID: "Portuguese_ReservedYoungMan", Language: "葡萄牙文", Name: "Reserved Young Man", SampleURL: "https://scene.vidu.zone/media-asset/035855-oQnIXx9ucDlTxRFp.mp3"},
	{VoiceID: "Portuguese_SmartYoungGirl", Language: "葡萄牙文", Name: "Smart Young Girl", SampleURL: "https://scene.vidu.zone/media-asset/035855-5h9TxVIUy8yq7ulL.mp3"},
	{VoiceID: "Portuguese_Kind-heartedGirl", Language: "葡萄牙文", Name: "Kind-hearted Girl", SampleURL: "https://scene.vidu.zone/media-asset/035855-xgWXj5fvfJMFlfcD.mp3"},
	{VoiceID: "Portuguese_Pompouslady", Language: "葡萄牙文", Name: "Pompous lady", SampleURL: "https://scene.vidu.zone/media-asset/035856-BSaHTj6rKm5fjzkx.mp3"},
	{VoiceID: "Portuguese_Grinch", Language: "葡萄牙文", Name: "Grinch", SampleURL: "https://scene.vidu.zone/media-asset/035856-iovsMZhW6bIdcOyl.mp3"},
	{VoiceID: "Portuguese_Debator", Language: "葡萄牙文", Name: "Debator", SampleURL: "https://scene.vidu.zone/media-asset/035856-wLQkVaEn4ltFKwfY.mp3"},
	{VoiceID: "Portuguese_SweetGirl", Language: "葡萄牙文", Name: "Sweet Girl", SampleURL: "https://scene.vidu.zone/media-asset/035856-XwSlnuwIu8ShiEeh.mp3"},
	{VoiceID: "Portuguese_AttractiveGirl", Language: "葡萄牙文", Name: "Attractive Girl", SampleURL: "https://scene.vidu.zone/media-asset/035856-R4vQmWuBLAgdKhWk.mp3"},
	{VoiceID: "Portuguese_ThoughtfulMan", Language: "葡萄牙文", Name: "Thoughtful Man", SampleURL: "https://scene.vidu.zone/media-asset/035856-RudMXh4sUyusfVtR.mp3"},
	{VoiceID: "Portuguese_PlayfulGirl", Language: "葡萄牙文", Name: "Playful Girl", SampleURL: "https://scene.vidu.zone/media-asset/035857-qUC9mEQIQwjkypXB.mp3"},
	{VoiceID: "Portuguese_GorgeousLady", Language: "葡萄牙文", Name: "Gorgeous Lady", SampleURL: "https://scene.vidu.zone/media-asset/035857-YumK9obwueApttqM.mp3"},
	{VoiceID: "Portuguese_LovelyLady", Language: "葡萄牙文", Name: "Lovely Lady", SampleURL: "https://scene.vidu.zone/media-asset/035857-LjaJCiavoulZ8qMp.mp3"},
	{VoiceID: "Portuguese_SereneWoman", Language: "葡萄牙文", Name: "Serene Woman", SampleURL: "https://scene.vidu.zone/media-asset/035857-Ofwsa1H50twRBl65.mp3"},
	{VoiceID: "Portuguese_SadTeen", Language: "葡萄牙文", Name: "Sad Teen", SampleURL: "https://scene.vidu.zone/media-asset/035857-qTI9KBW9aZguBPmg.mp3"},
	{VoiceID: "Portuguese_MaturePartner", Language: "葡萄牙文", Name: "Mature Partner", SampleURL: "https://scene.vidu.zone/media-asset/035857-TRbIdcLHSjdPrDm4.mp3"},
	{VoiceID: "Portuguese_Comedian", Language: "葡萄牙文", Name: "Comedian", SampleURL: "https://scene.vidu.zone/media-asset/035858-v9S79XJMHYC5AMVn.mp3"},
	{VoiceID: "Portuguese_NaughtySchoolgirl", Language: "葡萄牙文", Name: "Naughty Schoolgirl", SampleURL: "https://scene.vidu.zone/media-asset/035857-Zw6CdhgQdMVR2gn6.mp3"},
	{VoiceID: "Portuguese_Narrator", Language: "葡萄牙文", Name: "Narrator", SampleURL: "https://scene.vidu.zone/media-asset/035858-nZazjRA8D6itSIQa.mp3"},
	{VoiceID: "Portuguese_ToughBoss", Language: "葡萄牙文", Name: "Tough Boss", SampleURL: "https://scene.vidu.zone/media-asset/035858-DnCcxoFUSoy9kFWO.mp3"},
	{VoiceID: "Portuguese_Fussyhostess", Language: "葡萄牙文", Name: "Fussy hostess", SampleURL: "https://scene.vidu.zone/media-asset/035858-ytmj6ARG8wJY0zgU.mp3"},
	{VoiceID: "Portuguese_Dramatist", Language: "葡萄牙文", Name: "Dramatist", SampleURL: "https://scene.vidu.zone/media-asset/035858-xrZyimVJqko3sCMl.mp3"},
	{VoiceID: "Portuguese_Steadymentor", Language: "葡萄牙文", Name: "Steady Mentor", SampleURL: "https://scene.vidu.zone/media-asset/035859-1OYHXRajjtcdGHnt.mp3"},
	{VoiceID: "Portuguese_Jovialman", Language: "葡萄牙文", Name: "Jovial Man", SampleURL: "https://scene.vidu.zone/media-asset/035859-UAXsPyxBdOfwQBYu.mp3"},
	{VoiceID: "Portuguese_CharmingQueen", Language: "葡萄牙文", Name: "Charming Queen", SampleURL: "https://scene.vidu.zone/media-asset/035858-jL86FYAsVrayEr3t.mp3"},
	{VoiceID: "Portuguese_SantaClaus", Language: "葡萄牙文", Name: "Santa Claus", SampleURL: "https://scene.vidu.zone/media-asset/035859-RH6FvmBORiishhBp.mp3"},
	{VoiceID: "Portuguese_Rudolph", Language: "葡萄牙文", Name: "Rudolph", SampleURL: "https://scene.vidu.zone/media-asset/035859-AjmtEs1i35CNeNtP.mp3"},
	{VoiceID: "Portuguese_Arnold", Language: "葡萄牙文", Name: "Arnold", SampleURL: "https://scene.vidu.zone/media-asset/035859-oqiwsebuANXiPWzY.mp3"},
	{VoiceID: "Portuguese_CharmingSanta", Language: "葡萄牙文", Name: "Charming Santa", SampleURL: "https://scene.vidu.zone/media-asset/035900-3XWbqpa4vfztTO4E.mp3"},
	{VoiceID: "Portuguese_CharmingLady", Language: "葡萄牙文", Name: "Charming Lady", SampleURL: "https://scene.vidu.zone/media-asset/035859-hutvd6TgGMsoPs52.mp3"},
	{VoiceID: "Portuguese_Ghost", Language: "葡萄牙文", Name: "Ghost", SampleURL: "https://scene.vidu.zone/media-asset/035900-9xZwPXOCa4T7pQdn.mp3"},
	{VoiceID: "Portuguese_HumorousElder", Language: "葡萄牙文", Name: "Humorous Elder", SampleURL: "https://scene.vidu.zone/media-asset/035900-XkTYRMZgfW4kqUwF.mp3"},
	{VoiceID: "Portuguese_CalmLeader", Language: "葡萄牙文", Name: "Calm Leader", SampleURL: "https://scene.vidu.zone/media-asset/035900-yo1DNh5FHmfaLJ8I.mp3"},
	{VoiceID: "Portuguese_GentleTeacher", Language: "葡萄牙文", Name: "Gentle Teacher", SampleURL: "https://scene.vidu.zone/media-asset/035900-T3S61GdfYo3HexD0.mp3"},
	{VoiceID: "Portuguese_EnergeticBoy", Language: "葡萄牙文", Name: "Energetic Boy", SampleURL: "https://scene.vidu.zone/media-asset/035900-oFr6TDZwXmmO7v2A.mp3"},
	{VoiceID: "Portuguese_ReliableMan", Language: "葡萄牙文", Name: "Reliable Man", SampleURL: "https://scene.vidu.zone/media-asset/035900-mOO06UtkR3L3Z5sk.mp3"},
	{VoiceID: "Portuguese_SereneElder", Language: "葡萄牙文", Name: "Serene Elder", SampleURL: "https://scene.vidu.zone/media-asset/035900-N32UA3kyBBsGOSyF.mp3"},
	{VoiceID: "Portuguese_GrimReaper", Language: "葡萄牙文", Name: "Grim Reaper", SampleURL: "https://scene.vidu.zone/media-asset/035901-z8oylmGNYspuGGqJ.mp3"},
	{VoiceID: "Portuguese_AssertiveQueen", Language: "葡萄牙文", Name: "Assertive Queen", SampleURL: "https://scene.vidu.zone/media-asset/035901-f2hIpqsJUw0QAUQ8.mp3"},
	{VoiceID: "Portuguese_WhimsicalGirl", Language: "葡萄牙文", Name: "Whimsical Girl", SampleURL: "https://scene.vidu.zone/media-asset/035901-5OphYxHPDfwnb9dn.mp3"},
	{VoiceID: "Portuguese_StressedLady", Language: "葡萄牙文", Name: "Stressed Lady", SampleURL: "https://scene.vidu.zone/media-asset/035901-uWpA9FlhEmvgR2JN.mp3"},
	{VoiceID: "Portuguese_FriendlyNeighbor", Language: "葡萄牙文", Name: "Friendly Neighbor", SampleURL: "https://scene.vidu.zone/media-asset/035901-q7DRgysg08msA6jz.mp3"},
	{VoiceID: "Portuguese_CaringGirlfriend", Language: "葡萄牙文", Name: "Caring Girlfriend", SampleURL: "https://scene.vidu.zone/media-asset/035901-dYYDcfRCYqaAavGB.mp3"},
	{VoiceID: "Portuguese_PowerfulSoldier", Language: "葡萄牙文", Name: "Powerful Soldier", SampleURL: "https://scene.vidu.zone/media-asset/035902-xvV50q5t9Si9yhz2.mp3"},
	{VoiceID: "Portuguese_FascinatingBoy", Language: "葡萄牙文", Name: "Fascinating Boy", SampleURL: "https://scene.vidu.zone/media-asset/035902-HbIyHyv73BjwzX1d.mp3"},
	{VoiceID: "Portuguese_RomanticHusband", Language: "葡萄牙文", Name: "Romantic Husband", SampleURL: "https://scene.vidu.zone/media-asset/035902-OnCTfG9JOtNWtvpz.mp3"},
	{VoiceID: "Portuguese_StrictBoss", Language: "葡萄牙文", Name: "Strict Boss", SampleURL: "https://scene.vidu.zone/media-asset/035902-Z8rwVTZrF8aOQqhm.mp3"},
	{VoiceID: "Portuguese_InspiringLady", Language: "葡萄牙文", Name: "Inspiring Lady", SampleURL: "https://scene.vidu.zone/media-asset/035902-Dq43ofPynPKCWcDV.mp3"},
	{VoiceID: "Portuguese_PlayfulSpirit", Language: "葡萄牙文", Name: "Playful Spirit", SampleURL: "https://scene.vidu.zone/media-asset/035902-MBnqocwWFe2h7jiZ.mp3"},
	{VoiceID: "Portuguese_ElegantGirl", Language: "葡萄牙文", Name: "Elegant Girl", SampleURL: "https://scene.vidu.zone/media-asset/035902-vYnTwbBn3YUA5HWB.mp3"},
	{VoiceID: "Portuguese_CompellingGirl", Language: "葡萄牙文", Name: "Compelling Girl", SampleURL: "https://scene.vidu.zone/media-asset/035902-pMFk9vEGzSahc8oD.mp3"},
	{VoiceID: "Portuguese_PowerfulVeteran", Language: "葡萄牙文", Name: "Powerful Veteran", SampleURL: "https://scene.vidu.zone/media-asset/035902-XRyXNCeGd69A6DTh.mp3"},
	{VoiceID: "Portuguese_SensibleManager", Language: "葡萄牙文", Name: "Sensible Manager", SampleURL: "https://scene.vidu.zone/media-asset/035903-J4MWHZ4NdSpD0MSV.mp3"},
	{VoiceID: "Portuguese_ThoughtfulLady", Language: "葡萄牙文", Name: "Thoughtful Lady", SampleURL: "https://scene.vidu.zone/media-asset/035903-l7SdRhUPCnKkE37N.mp3"},
	{VoiceID: "Portuguese_TheatricalActor", Language: "葡萄牙文", Name: "Theatrical Actor", SampleURL: "https://scene.vidu.zone/media-asset/035903-5h7YzW7aBEEZjEyG.mp3"},
	{VoiceID: "Portuguese_FragileBoy", Language: "葡萄牙文", Name: "Fragile Boy", SampleURL: "https://scene.vidu.zone/media-asset/035903-444V6STPDnIA8rlC.mp3"},
	{VoiceID: "Portuguese_ChattyGirl", Language: "葡萄牙文", Name: "Chatty Girl", SampleURL: "https://scene.vidu.zone/media-asset/035903-KlRb6Hac52sRZpia.mp3"},
	{VoiceID: "Portuguese_Conscientiousinstructor", Language: "葡萄牙文", Name: "Conscientious Instructor", SampleURL: "https://scene.vidu.zone/media-asset/035903-1qJIzbA1njepzwb0.mp3"},
	{VoiceID: "Portuguese_RationalMan", Language: "葡萄牙文", Name: "Rational Man", SampleURL: "https://scene.vidu.zone/media-asset/035904-6tXudawKmYULpkMH.mp3"},
	{VoiceID: "Portuguese_WiseScholar", Language: "葡萄牙文", Name: "Wise Scholar", SampleURL: "https://scene.vidu.zone/media-asset/035904-m9OqbjpCSb1ptKNX.mp3"},
	{VoiceID: "Portuguese_FrankLady", Language: "葡萄牙文", Name: "Frank Lady", SampleURL: "https://scene.vidu.zone/media-asset/035904-nkMHVAax7JlOaSXK.mp3"},
	{VoiceID: "Portuguese_DeterminedManager", Language: "葡萄牙文", Name: "Determined Manager", SampleURL: "https://scene.vidu.zone/media-asset/035904-GeDXhMqAPWrLCtUO.mp3"},
	{VoiceID: "French_Male_Speech_New", Language: "法文", Name: "Level-Headed Man", SampleURL: "https://scene.vidu.zone/media-asset/035756-rxEBofqGwhif5qng.mp3"},
	{VoiceID: "French_Female_News Anchor", Language: "法文", Name: "Patient Female Presenter", SampleURL: "https://scene.vidu.zone/media-asset/035756-yh2jpcYujGATdrnL.mp3"},
	{VoiceID: "French_CasualMan", Language: "法文", Name: "Casual Man", SampleURL: "https://scene.vidu.zone/media-asset/035756-UsNNaEJULdSii82b.mp3"},
	{VoiceID: "French_MovieLeadFemale", Language: "法文", Name: "Movie Lead Female", SampleURL: "https://scene.vidu.zone/media-asset/035756-o2mEO0ijNHbHGRwy.mp3"},
	{VoiceID: "French_FemaleAnchor", Language: "法文", Name: "Female Anchor", SampleURL: "https://scene.vidu.zone/media-asset/035756-0WMICpjG4qdi5xhp.mp3"},
	{VoiceID: "French_MaleNarrator", Language: "法文", Name: "Male Narrator", SampleURL: "https://scene.vidu.zone/media-asset/035756-Lhz9XAfklUL4yrLr.mp3"},
	{VoiceID: "Indonesian_SweetGirl", Language: "印尼文", Name: "Sweet Girl", SampleURL: "https://scene.vidu.zone/media-asset/035653-j1Y3keTo6DShfEzD.mp3"},
	{VoiceID: "Indonesian_ReservedYoungMan", Language: "印尼文", Name: "Reserved Young Man", SampleURL: "https://scene.vidu.zone/media-asset/035653-ohNuxDbeZc6uTtoU.mp3"},
	{VoiceID: "Indonesian_CharmingGirl", Language: "印尼文", Name: "Charming Girl", SampleURL: "https://scene.vidu.zone/media-asset/035653-ZIwlswQLA9qmTdU7.mp3"},
	{VoiceID: "Indonesian_CalmWoman", Language: "印尼文", Name: "Calm Woman", SampleURL: "https://scene.vidu.zone/media-asset/035653-oweTzCEudUlPnAFI.mp3"},
	{VoiceID: "Indonesian_ConfidentWoman", Language: "印尼文", Name: "Confident Woman", SampleURL: "https://scene.vidu.zone/media-asset/035653-czxnaGSlJ3ZWFDQV.mp3"},
	{VoiceID: "Indonesian_CaringMan", Language: "印尼文", Name: "Caring Man", SampleURL: "https://scene.vidu.zone/media-asset/035653-5IfsR8TbYoQChgKz.mp3"},
	{VoiceID: "Indonesian_BossyLeader", Language: "印尼文", Name: "Bossy Leader", SampleURL: "https://scene.vidu.zone/media-asset/035654-co5jmEYbQtFRmUqM.mp3"},
	{VoiceID: "Indonesian_DeterminedBoy", Language: "印尼文", Name: "Determined Boy", SampleURL: "https://scene.vidu.zone/media-asset/035654-zBp6jTlUpfPPuU0G.mp3"},
	{VoiceID: "Indonesian_GentleGirl", Language: "印尼文", Name: "Gentle Girl", SampleURL: "https://scene.vidu.zone/media-asset/035654-IdUBETC49ObxAB4G.mp3"},
	{VoiceID: "German_FriendlyMan", Language: "德文", Name: "Friendly Man", SampleURL: "https://scene.vidu.zone/media-asset/035621-aCq5cdqQW43pB8ct.mp3"},
	{VoiceID: "German_SweetLady", Language: "德文", Name: "Sweet Lady", SampleURL: "https://scene.vidu.zone/media-asset/035621-LuolmiKVVesy5hTY.mp3"},
	{VoiceID: "German_PlayfulMan", Language: "德文", Name: "Playful Man", SampleURL: "https://scene.vidu.zone/media-asset/035621-E4Ucg8YwiueVTepF.mp3"},
	{VoiceID: "Russian_HandsomeChildhoodFriend", Language: "俄文", Name: "Handsome Childhood Friend", SampleURL: "https://scene.vidu.zone/media-asset/035504-F9VKfKDNyrUjIDXp.mp3"},
	{VoiceID: "Russian_BrightHeroine", Language: "俄文", Name: "Bright Queen", SampleURL: "https://scene.vidu.zone/media-asset/035504-rz3mB6An408J7O87.mp3"},
	{VoiceID: "Russian_AmbitiousWoman", Language: "俄文", Name: "Ambitious Woman", SampleURL: "https://scene.vidu.zone/media-asset/035504-UacsdEy0A4ftk3Cv.mp3"},
	{VoiceID: "Russian_ReliableMan", Language: "俄文", Name: "Reliable Man", SampleURL: "https://scene.vidu.zone/media-asset/035505-DyEhHRWGSCmoD7sy.mp3"},
	{VoiceID: "Russian_CrazyQueen", Language: "俄文", Name: "Crazy Girl", SampleURL: "https://scene.vidu.zone/media-asset/035505-FIDsbXD0MlA24Fqd.mp3"},
	{VoiceID: "Russian_PessimisticGirl", Language: "俄文", Name: "Pessimistic Girl", SampleURL: "https://scene.vidu.zone/media-asset/035505-NbPMW7x5dIOFqoFw.mp3"},
	{VoiceID: "Russian_AttractiveGuy", Language: "俄文", Name: "Attractive Guy", SampleURL: "https://scene.vidu.zone/media-asset/035506-XHTn8GohW6Xanqcd.mp3"},
	{VoiceID: "Russian_Bad-temperedBoy", Language: "俄文", Name: "Bad-tempered Boy", SampleURL: "https://scene.vidu.zone/media-asset/035506-JZ8O4tOrI74ttkS1.mp3"},
	{VoiceID: "Italian_BraveHeroine", Language: "意大利文", Name: "Brave Heroine", SampleURL: "https://scene.vidu.zone/media-asset/035417-4BRNfRUWeCEqi1OV.mp3"},
	{VoiceID: "Italian_Narrator", Language: "意大利文", Name: "Narrator", SampleURL: "https://scene.vidu.zone/media-asset/035417-efHRj1jLnPYICek8.mp3"},
	{VoiceID: "Italian_WanderingSorcerer", Language: "意大利文", Name: "Wandering Sorcerer", SampleURL: "https://scene.vidu.zone/media-asset/035417-eFDy6VsgM4XQrW6A.mp3"},
	{VoiceID: "Italian_DiligentLeader", Language: "意大利文", Name: "Diligent Leader", SampleURL: "https://scene.vidu.zone/media-asset/035417-BFDEwSWARMORQEpt.mp3"},
	{VoiceID: "Arabic_CalmWoman", Language: "阿拉伯文", Name: "Calm Woman", SampleURL: "https://scene.vidu.zone/media-asset/035240-u12liEq8DtchndBf.mp3"},
	{VoiceID: "Arabic_FriendlyGuy", Language: "阿拉伯文", Name: "Friendly Guy", SampleURL: "https://scene.vidu.zone/media-asset/035240-QHVeX8jxCAHCOM1x.mp3"},
	{VoiceID: "Turkish_CalmWoman", Language: "土耳其文", Name: "Calm Woman", SampleURL: "https://scene.vidu.zone/media-asset/035209-qy1MxzMRbLQPEx5f.mp3"},
	{VoiceID: "Turkish_Trustworthyman", Language: "土耳其文", Name: "Trustworthy man", SampleURL: "https://scene.vidu.zone/media-asset/035209-Md7ztqRkrvs3mXJH.mp3"},
	{VoiceID: "Ukrainian_CalmWoman", Language: "乌克兰文", Name: "Calm Woman", SampleURL: "https://scene.vidu.zone/media-asset/034930-ELzwPhKz4Q3UiOyA.mp3"},
	{VoiceID: "Ukrainian_WiseScholar", Language: "乌克兰文", Name: "Wise Scholar", SampleURL: "https://scene.vidu.zone/media-asset/034930-STPANqlkjzZwA87W.mp3"},
	{VoiceID: "Dutch_kindhearted_girl", Language: "荷兰文", Name: "Kind-hearted girl", SampleURL: "https://scene.vidu.zone/media-asset/034802-8UbeAa4QGbB6JaZx.mp3"},
	{VoiceID: "Dutch_bossy_leader", Language: "荷兰文", Name: "Bossy leader", SampleURL: "https://scene.vidu.zone/media-asset/034802-5PctlXu118SHucvd.mp3"},
	{VoiceID: "Vietnamese_kindhearted_girl", Language: "越南文", Name: "Kind-hearted girl", SampleURL: "https://scene.vidu.zone/media-asset/034727-vLCYIZiGCweFE3TC.mp3"},
}

// DefaultVoices 官方音色表（seed 源——main 启动时表空则写入）。
func DefaultVoices() []entity.GenerationVoice { return defaultVoices }
